version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginxinrproject
    ports:
      - "9993:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpinrproject
      - mysqlinrproject
    networks:
      - laravel

  mysqlinrproject:
    image: mysql:5.7.29
    container_name: mysqlinrproject
    restart: unless-stopped
    tty: true
    ports:
      - "3349:3349"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  phpinrproject:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpinrproject
    volumes:
      - ./src:/var/www/html
    ports:
      - "9800:9800"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composerinrproject
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - phpinrproject
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: npminrproject
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisaninrproject
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysqlinrproject
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel