version: '2'
services:
  laravel:
    container_name: laravel-autoemail-prod
    image : laravel-autoemail-test
    ports:
      - "5000:80"
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes: 
      - auto-email-docs-prod:/var/www/html/public/docs/

  mysql:
    image: mysql:5.6.36
    volumes:
       - autoemaildb_data_prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=email
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
    ports:
      - "5111:3306"
      
volumes:
    autoemaildb_data_prod:
    auto-email-docs-prod: